version: '3.3'

services:
  mysql:
    image: mysql:5.7
    depends_on:
      - leadgen_web
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_USER=espocrm
      - MYSQL_DATABASE=espocrm
      - MYSQL_PASSWORD=h!!?F:_-O^Jp+TB4B*HYt3
      - MYSQL_ROOT_PASSWORD=k**:-_U^Jp+TY4B*EFbE
    ports:
      - "33060:33060"
      - "3306:3306"
    networks:
      - leadgen
    restart: always
  espocrm:
    image: leen15/espocrm:v5.7.0
    depends_on:
      - mysql
    volumes:
      - ./espocrm:/var/www/data:rw
    ports:
      - "8081:80"
    networks:
      - leadgen
    restart: always
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    networks:
      - leadgen
    volumes:
      - ./mssql:/var/opt/mssql:rw
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=*k_U^Jp+PZ6*CDmQ
    restart: always
  leadgen_web:
    image: xtonyx/leadgenweb:latest
    depends_on:
      - mssql
    ports:
      - "8080:80"
    networks:
      - leadgen
    environment:
      - sqlConnectionString=Data Source=mssql;Initial Catalog=LeadGenDB;User ID=sa;Password=*k_U^Jp+PZ6*CDmQ;
    restart: always
networks:
  leadgen:
    driver: bridge