#https://medium.freecodecamp.org/docker-compose-nginx-and-letsencrypt-setting-up-website-to-do-all-the-things-for-that-https-7cb0bf774b7e

version: '3.3'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    volumes:
      - /home/anton/leadgen/mssql:/var/opt/mssql
    networks:
      - leadgen-core
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=pass@word1
  app:
    image: xtonyx/leadgenweb:20190408012845
    ports:
      - "8080:80"
    networks:
      - leadgen-core
    environment:
      - sqlConnectionString=Data Source=mssql;Initial Catalog=LeadGenDB;User ID=sa;Password=pass@word1;
    depends_on:
      - mssql
    restart: on-failure
  nginx:
    image: linuxserver/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/anton/leadgen/nginxVolume:/config 
    depends_on:
      - app
    restart: on-failure
    networks:
      - leadgen-core
    environment:
      - PUID=1001 # get on dockerhost through command "id <user>""
      - PGID=1001
      - EMAIL=anton.ozolin@gmail.com
      - URL=ubuntu.ozolin.ru
      # - SUBDOMAINS=www
      - TZ=America/LosAngeles
      - VALIDATION=http # using dns validation
      - DNSPLUGIN=dnsimple # via dnsimple, note there is additional configuration require separate from this file
      - STAGING=true # this should be uncommented when testing for initial success, to avoi   d some rate limiting

networks:
  leadgen-core:
    driver: bridge