#https://medium.freecodecamp.org/docker-compose-nginx-and-letsencrypt-setting-up-website-to-do-all-the-things-for-that-https-7cb0bf774b7e
#docker-compose up -d --no-deps --build app

version: '3.3'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    networks:
      - leadgen_core
    volumes:
      - /home/anton/leadgen/mssql:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=*k_U^Jp+PZ6*CDmQ
    restart: on-failure
  app:
    image: xtonyx/leadgenweb:20190429122505
    depends_on:
      - mssql
    ports:
      - "8080:80"
    networks:
      - leadgen_core
    environment:
      - sqlConnectionString=Data Source=mssql;Initial Catalog=LeadGenDB;User ID=sa;Password=*k_U^Jp+PZ6*CDmQ;
    restart: on-failure
  nginx:
    image: linuxserver/letsencrypt
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    networks:
      - leadgen_core
    volumes:
      - /home/anton/leadgen/nginxVolume:/config
    environment:
      - PUID=1001 # get on dockerhost through command "id <user>""
      - PGID=1001
      - EMAIL=anton.ozolin@gmail.com
      - URL=winecellars.pro
      - SUBDOMAINS=www
      - TZ=America/LosAngeles
      - VALIDATION=http # using dns validation
      - DNSPLUGIN=dnsimple # via dnsimple, note there is additional configuration require separate from this file
      #- STAGING=true # this should be uncommented when testing for initial success, to avoi   d some rate limiting
    restart: on-failure

networks:
  leadgen_core:
    driver: bridge