version: '3.3'

services:
  mssql:
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    networks:
      - leadgen
    volumes:
      - ./mssql:/var/opt/mssql:rw
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=*k_U^Jp+PZ6*CDmQ
    restart: always
  leadgen_web:
    image: xtonyx/leadgenweb:latest
    depends_on:
      - mssql
    ports:
      - "8080:80"
    networks:
      - leadgen
    environment:
      - sqlConnectionString=Data Source=db.winecellars.pro;Initial Catalog=LeadGenDB_prod;User ID=LeadGenDB_prod;Password=*k_U^Jp+PZ6*CDmQ;
    restart: always
networks:
  leadgen:
    driver: bridge