CREATE TABLE [dbo].[CMSAttachmentType](
	[AttachmentTypeID] [int] NOT NULL,
	[AttachmentTypeName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_CMSAttachmentType] PRIMARY KEY CLUSTERED 
(
	[AttachmentTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]