CREATE TABLE [dbo].[LeadLocation](
	[LocationID] [bigint] NOT NULL,
	[LeadID] [bigint] NOT NULL,
 CONSTRAINT [PK_LeadLocation] PRIMARY KEY CLUSTERED 
(
	[LocationID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_LeadLocation_Unique] UNIQUE NONCLUSTERED 
(
	[LocationID] ASC,
	[LeadID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY])
GO
ALTER TABLE [dbo].[LeadLocation]  WITH CHECK ADD  CONSTRAINT [FK_Lead.Location_Lead] FOREIGN KEY([LeadID])
REFERENCES [dbo].[Lead] ([LeadID])
GO

ALTER TABLE [dbo].[LeadLocation] CHECK CONSTRAINT [FK_Lead.Location_Lead]
GO
ALTER TABLE [dbo].[LeadLocation]  WITH CHECK ADD  CONSTRAINT [FK_LeadLocationId] FOREIGN KEY([LocationId])
REFERENCES [dbo].[Location] ([LocationId])