CREATE TABLE [dbo].[LeadFieldType](
	[FieldTypeID] [int] NOT NULL,
	[FieldTypeName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_LeadFieldType] PRIMARY KEY CLUSTERED 
(
	[FieldTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]