CREATE TABLE [dbo].[LeadFieldStructureGroup](
	[GroupID] [int] IDENTITY(1,1) NOT NULL,
	[GroupCode] [nvarchar](100) NOT NULL,
	[GroupTitle] [nvarchar](255) NULL,
	[GroupOrder] [int] NULL,
 CONSTRAINT [PK_LeadFieldStructureGroup] PRIMARY KEY CLUSTERED 
(
	[GroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_LeadFieldStructureGroup] UNIQUE NONCLUSTERED 
(
	[GroupID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]