CREATE TABLE [dbo].[LeadReviewMeasure](
	[MeasureID] [smallint] NOT NULL,
	[MeasureName] [nvarchar](255) NOT NULL,
	[Order] [smallint] NULL,
 CONSTRAINT [PK_ReviewMeasure] PRIMARY KEY CLUSTERED 
(
	[MeasureID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [IX_ReviewMeasure] UNIQUE NONCLUSTERED 
(
	[MeasureName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]