CREATE TABLE [dbo].[SystemOptions](
	[OptionKey] [nvarchar](100) NOT NULL,
	[OptionValue] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_SystemOptions] PRIMARY KEY CLUSTERED 
(
	[OptionKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]