CREATE TABLE [dbo].[Taxonomy](
	[TaxonomyID] [int] IDENTITY(1,1) NOT NULL,
	[TaxonomyCode] [nvarchar](50) NOT NULL,
	[TaxonomyName] [nvarchar](50) NOT NULL,
	[IsTag] [bit] NOT NULL,
 CONSTRAINT [PK_CMSTaxonomy] PRIMARY KEY CLUSTERED 
(
	[TaxonomyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Taxonomy] ADD  CONSTRAINT [DF_Taxonomy_IsTag]  DEFAULT ((0)) FOR [IsTag]
GO
/****** Object:  Index [IX_Taxonomy]    Script Date: 5/9/2017 10:43:55 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Taxonomy] ON [dbo].[Taxonomy]
(
	[TaxonomyCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
/****** Object:  Index [IX_Taxonomy_1]    Script Date: 5/9/2017 10:43:55 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Taxonomy_1] ON [dbo].[Taxonomy]
(
	[TaxonomyName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]