name: Publish To Docker Hub and Deploy to Web Server

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GIT_TAG: ${GITHUB_REF/refs\/tags\//}
    steps:
    - uses: actions/checkout@v1
    - name: Update Web Server
      uses: appleboy/ssh-action@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        LEADGEN_DB_CONNECTION_STRING: ${{ secrets.LEADGEN_DB_CONNECTION_STRING }}
      with:
        host: ${{ secrets.WEB_SSH_HOST }}
        username: ${{ secrets.WEB_SSH_USERNAME }}
        password: ${{ secrets.WEB_SSH_PASSWORD }}
        port: ${{ secrets.WEB_SSH_PORT }}
        envs: DOCKER_USERNAME,LEADGEN_DB_CONNECTION_STRING
        script: |
         GIT_TAG=${GITHUB_REF/refs\/tags\//}
         cd /opt/leadgen
         echo $GIT_TAG >> logfile.txt
         echo $DOCKER_USERNAME >> logfile.txt
         echo $LEADGEN_DB_CONNECTION_STRING >> logfile.txt
