name: Publish To Docker Hub

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Update Web Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOME_SSH_HOST }}
        username: ${{ secrets.HOME_SSH_USERNAME }}
        password: ${{ secrets.HOME_SSH_PASSWORD }}
        port: ${{ secrets.HOME_SSH_PORT }}
        script: |
         /opt/leadgen/docker_compose_update_leadgenweb.sh
