name: Publish To Docker Hub and Deploy to Web Server

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Build the Docker image
      run: docker build . --file LeadGen.Web/Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/leadgenweb:latest
    - name: Publish the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/leadgenweb:latest
    - name: Update Web Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
         /opt/leadgen/docker_compose_update_leadgenweb.sh
